### ISSUE TITLE
Embedded PDFs do not render

### ISSUE THREAD

**Issue by gitterspec** [CookieJarApps/SmartCookieWeb-Preview#121]
For example: https://eamena.org/embedded-pdf-test

It simply prompts to download the file. For some other websites, there is no download prompt either, making the PDF completely inaccessible. 

Works fine in Firefox, IceRaven, etc.

Using latest Preview release from GitHub.

**Comment by CookieJarApps** [comment]
It could be that the version of GeckoView of the latest Preview release doesn't have PDF.js, and that Mozilla have added it since (which is why it works in Firefox). Could you try with this Firefox addon installed: https://addons.mozilla.org/en-US/android/addon/android-pdf-js/
In any case, I'll work on an update for the browser with an updated GeckoView version.
Thanks!

**Comment by gitterspec** [comment]
Works with the addon. Thanks.

**Comment by CookieJarApps** [comment]
This should now work with no add-on as of the latest update
