### ISSUE TITLE
Unable to load add-on settings ("Failed to query Add-ons!")

### ISSUE THREAD

**Issue by parcelcat** [CookieJarApps/SmartCookieWeb-Preview#129]
On version 21.0, when entering the Add-on settings, no add-ons are shown (including ones that have already been installed/sideloaded).

Instead, the "Loading add-ons..." loading bar is stuck, a question mark symbol with the label "No results" is shown on top of the loading bar, and then a "Failed to query Add-ons!" toast notification pops up.

**Comment by CookieJarApps** [comment]
I can't seem to recreate the issue on my end. I'd suggest that the Firefox add-on server might be blocked on your connection or something, but SCWP proxies the requests to Mozilla's servers so I don't think that's the issue. Could you check if the add list on the website (https://smartcookieweb.com/addons) loads correctly for you? The add-on list on the site is pulled from the API client side so if something is wrong the issue might show up there too.

**Comment by daffydock** [comment]
Is what you are requesting is to go to https://smartcookieweb.com/addons? See what comes up?

I run Ublock on Medium mode, so of course it would not load correctly. Fixed it. Loads no problem.
Now, when I click on say, _Download_, on any Add-on, the browser then switches over to the Add-Ons page.

After a few seconds, I get the "Failed to query Add-ons!," toast. As I mentioned in my other Issue, it happens in different Forks, not just on yours. 

Since it does seem to work fine on FF Beta when I tested. I assumed that either it might be a settings issue on About:Config --which I was not able to figure out what was different when I checked-- or there is some other variable that I am not aware.  Since I also use Mull and noticed this error there first. Worth noting that Add-ons and the page in general were working fine on 20.1. Only became an issue once I update to Ver. 21.0.  

I have access to a couple of phones and noticed this happens to both:
 app-armeabi-v7a-release.apk 
 app-arm64-v8a-release.apk 
 
 I am on a VPN but issue happens either way. Not that it should matter if it works on FF Beta with the VPN on.

**Comment by CookieJarApps** [comment]
Mozilla have made some big changes to the add-on system in Android Components to expand add-on support in Firefox for Android, changes that only made their way into SCW in 21.0 (and would also be in new updates of any other Firefox forks), so something to do with that could be causing the issue. I'll test the app on some other devices to see if I can find out what's going on.

**Comment by barclayslb** [comment]
Hello there,

I found the problem, I have had the same after updating the application from 20.1 to 21.0.
It's related to the custom add on collection that was wiped out (credentials was empty).
After I enter back my custom add on collection, the add-on setting page is loading again and add-ons are working as expected.

Just need to go the parameters > advanced parameters
You will need to check (it was disabled) "Use a custom module store"
After that you will need to fill those parameters
- Creator of the collection (user ID)
- Collection name (name of the collection)

It should works thereafter.

**Comment by daffydock** [comment]
> Hello there,
> 
> I found the issue, I have had the same problem after updating the application from 20.1 to 21.0. It's related to the custom add on collection that was wiped out (credentials was empty). After I enter back my custom add on collection, the add-on setting page is loading again and add-ons are working as expected.
> 
> Just need to go to '_parameters > advanced parameters_'
> 
> You will need to check (it was disabled) "Use a custom module store"
> 
> After that, you will need to fill those parameters :
> 
>     * Creator of the collection (user ID)
> 
>     * Collection name (name of the collection)
> 
> 
> It should works thereafter.

_Parameters?_ Did you mean _Settings?_
If that is the case, then no, that is not the fix. I tried enabling it before. Used my own collection, Iceraven's collection, a test collection and even Ghack.net's collection. No changes. 

About the only thing I have not done is signed into my Firefox, well, soon to be Mozilla account. Are you signed on?  

----

@CookieJarApps I had thought the incoming changes could be a factor. Just odd that FF Beta works and without having to signing in. I will wait to see what you are able to find out. Thanks.

**Comment by barclayslb** [comment]
Parameters , I mean settings yes
I have not sign on Mozilla account, no need to
That's weird that is not working after that for you

**Comment by daffydock** [comment]
Just as a FYI, downloaded latest FF Nightly (121.+) a couple of days ago and add-ons work right out of the box. In fact, I was able to easily install LibreRedirect from from the Add-on page. No special or any Collection at all had to be added.

**Comment by CookieJarApps** [comment]
I'll release an update with the latest Mozilla Android Components update and see if that helps. If not, this could possibly be an issue with transferring add-ons over from the previous version, as I can't recreate the issue with a fresh install.

**Comment by daffydock** [comment]
*Fingers crossed* that updating to latest will fix the issue. It seems that it fixes the issue on other forks and newer FF versions that have checked on the same phone. Since as preference, I rather use both Mull and your CookieWeb Preview  over the others.  

I compared some relevant values that I could find on about:config and likely missed something but from what I compared, they were all the same values. So, no idea what causes it. 

I really like using CWP and the way I have set the add-ons on it, so I have not reinstalled. I did try reinstalling Mull 118, and later 119+ and it did not fix it. Hoping that he updates too, and see what happens. However, on my newer phone, Mull works after the latest update but it still does not work on my older, daily driver. 

I am using the Arm7 version, if that makes a difference.

**Comment by svendsvin** [comment]
I have the same problem as parcelcat on v. 21.0. I haven't transferred any add-ons since it's the first time I install SCWP. I only use one custom add-on.

**Comment by daffydock** [comment]
Installed latest, which is Ver. 22 as we discussed @CookieJarApps and without doing anything else, went into the browser's add-ons settings and it just works. Out of the box. Likely, it was due to something being done behind the scenes at Mozilla. As I touched on earlier, Mull, which is currently based on Ver.119+ still does not work. So likely the issue was fixed in 120+.

As far I can see, issue is now fixed. Guess we will have to see what @parcelcat says. Great to have the browser back to normal. Thanks!

**Comment by daffydock** [comment]
Would it be reasonable to go ahead and close this issue? I mean, it appears fixed for almost 6 months now. It is highly likely that it also fixed the issue put forth by @parcelcat.

Up to you @CookieJarApps

**Comment by CookieJarApps** [comment]
> Would it be reasonable to go ahead and close this issue? I mean, it appears fixed for almost 6 months now. It is highly likely that it also fixed the issue put forth by @parcelcat.
> 
> Up to you @CookieJarApps  

Yes, I'll close this now - thanks!
