### ISSUE TITLE
[Addons Request] Search by Image

### ISSUE THREAD

**Issue by DayatXD** [CookieJarApps/SmartCookieWeb-Preview#28]
i tried using search by image with addons collection but it didn't work or bugged when im trying to upload a image, it just stuck and doesn't search the result

**Comment by CookieJarApps** [comment]
Sorry about that, here's how it works on my device:

https://user-images.githubusercontent.com/44752343/117185670-fd0a1a80-add1-11eb-8d14-29afec6d80ed.mp4

Is the issue on yours that nothing happens when you select the image, or that once the tab with the image search is opened, the page loads very slowly / doesn't load at all?

**Comment by DayatXD** [comment]
its working fine now when tried lastest version 6.0, so imma close this issue.
