### ISSUE TITLE
Feature Request: Built-in Support for VideoDL Or Selection Action Menu for Videos:

### ISSUE THREAD

**Issue by Jpersh27** [CookieJarApps/SmartCookieWeb-Preview#6]
Hello @CookieJarApps

I have two new feature request suggestions regarding your Biscuit Browser application.

1 • I think that many users would benefit from a new feature that would see the implementation of your VideoDL application into the the Biscuit Browser and support the ability to download Video Files and Ability to capture them directly within the Browser, and download to your device storage.

(Instead of having to copy and paste the URL into the external VideoDL application everytime you want to download a new Video file) 

2 • Ability to Long press on a video to trigger the Selection Action Menu. (Upon doing this action it gives you three different options to chose from) 

They are in order and listed below: 
1.) Copy link
2.) Share Link
3.) Save file to device

(The third and final option is the one that needs to be supported to download video files to your device storage) 

• It shows a Web API in the form of a blob object string and everytime you perform this long press action the following shows up on the screen: blob:https://www. 

https://developer.mozilla.org/en-US/docs/Web/API/Blob

**Comment by CookieJarApps** [comment]
I had a few different ideas for how to add VideoDL support to the app:
- I could add a toolbar item, like SmartCookieWeb, but the problem is that I'm not sure if I can detect videos on the page like I do with WebView, so it'd probably be there all the time.
- Instead, though, I could add an option to the dropdown menu.
- Another option would be to make an add-on - it wouldn't be possible to embed youtube-dl into the extension, but either I could make one that downloads the video by sending the URL to a server and getting the download URL (but that might not be the best option for privacy), I could make the add-oninclude some buttons for various video/audio download resolutions that redirect to the app and automatically starts a download with the selected options, or I could update VideoDL to have an option to run a webserver on the device which communicates with the add-on and allows video download directly within the browser without any external servers.
