### ISSUE TITLE
Longer term plans

### ISSUE THREAD

**Issue by htsmi** [CookieJarApps/SmartCookieWeb-Preview#64]
This isn't really a bug but I wasn't sure where else to ask. Seeing as this is now called SmartCookieWeb-Preview, are you planning to replace SmartCookieWeb with this browser? If that is the case, what are your longer term plans for functionality and interface – currently the interface of this browser seems to have a lot borrowed from Fenix and I honestly prefer what you've created with SmartCookieWeb – it just seems more intuitive in so many ways. I'm one of those Fennec die-hards who never found a perfect replacement, although SmartCookieWeb comes close. I would just hate to lose that again!

Some of the reasons I was never able to adjust to Fenix:
* Trying to push me into using top sites, collections, whatever rather than bookmarks
* Hiding bookmarks deep in a menu
* Really bad bookmark navigation, they always open in a new tab for no reason and hitting the back button takes me to the top level so I lose track of the folder I was in
* No about:config to turn off the offensive telemetry
* Removal of one-tap search engine selection
* URL/search term entry page is decisively harder to navigate, no simple access to bookmarks or history
* Removal of desktop-style tabs and forward, back, reload buttons in URL toolbar
* Just a ridiculous increase in taps required to access basic functions

Of course this browser is not Fenix, I just want to give an idea of the things that sent me your direction which may possibly be the same for others. SmartCookieWeb handles all these things pretty great, and is also faster due to some Fennec addon features being in the core. Just curious where you are headed with all of this. I really do appreciate all the hard work, in both projects you have made it look easy to do what major browsers have dragged their feet on for years!

**Comment by CookieJarApps** [comment]
Great to hear you like SmartCookieWeb!

This browser won't replace SmartCookieWeb, and SCW will continue receiving updates, but I'll put a note in the README strongly recommending that people move to this browser once the first stable release is out.

At the moment, this browser uses Mozilla Android Components for some of the browser features and parts of the UI to speed up the development and improve stability, so that's why parts of the interface are similar to Fenix. Once I've fixed some of the bugs in the browser and added most of the features I want for the first stable release, I'll start removing Android Components parts with the goal of replacing them all entirely. The long-term aim is to recreate the SCW UI as closely as possible.

Desktop tabs, action buttons in the drawers and better tablet UI is coming in one of the next few updates.

**Comment by htsmi** [comment]
That is great! I'm sure a lot of us Fennec refugees will be pleased to hear this. Again thanks for being so responsive, especially to someone like me who hasn't been able to offer a line of code. I think I'll mark this closed since it's not a real bug and the real stuff is being tracked elsewhere.
